<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Programming &gt; Shows</h1>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Shows</h6>
            </div>

            <div class="card-body">
                <table class="table table-borderless">
                    <thead class="thead-dark">
                        <tr style="font-weight: bold;">
                            <td scope="col" style="width: 50%">Name</td>
                            <td scope="col" style="width: 10%">Frames</td>
                            <td scope="col" style="width: 20%">Length</td>
                            <td scope="col" style="width: 20%">Actions</td>
                        </tr>
                    </thead>

                    <tbody>
                        <?php $shows = \VRPilot\Show::all();
                        foreach ($shows as $show) { ?>
                            <tr class="success">
                                <td><?php print($show->getName()) ?></td>
                                <td colspan="2"><?php print($show->getId()) ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>